# マイグレーション schema.prismaの内容をDBに反映する
migrate:
	npx prisma migrate dev

# schema.prismaの内容からモデル型を作成する
generate:
	npx prisma generate

# DBにseedデータ挿入
seed:
	npx tsx prisma/seed/seed.ts

# storybook開始
story:
	npm run storybook