version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    tty: true

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    # environment:
    #   - DATABASE_URL=postgres://user:password@localhost:5432/aptitude-quiz-master?sslmode=disable
    # links:
    #   - db:db

  db:
    image: postgres
    environment:
      POSTGRES_DB: aptitude-quiz-master
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
